# Generated by Django 4.0.6 on 2022-07-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_issue',
            field=models.TextField(null=True),
        ),
    ]
