# Generated by Django 4.0.6 on 2022-07-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patient_patient_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_issue',
            new_name='issue',
        ),
    ]
