# Generated by Django 4.0.6 on 2022-07-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('core', '0004_rename_patient_issue_patient_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.doctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
